#!/bin/bash
echo "╔══════════════════════════════════════╗"
echo "║     📊 C2 STATUS DASHBOARD          ║"
echo "╚══════════════════════════════════════╝"
echo ""
LOG_DIR="$HOME/c2_server/logs"
echo "TCP Connections:"
tail -5 "$LOG_DIR/c2_sessions.log" 2>/dev/null || echo "  No connections yet"
echo ""
echo "HTTP Requests:"
tail -5 "$LOG_DIR/c2_http.log" 2>/dev/null || echo "  No requests yet"
echo ""
echo "C2 Status Log:"
tail -3 "$LOG_DIR/c2_status.log" 2>/dev/null || echo "  No status log"
